title: MyAgency.gov
email: hello@MyAgency.gov
description: >-
  My agency rocks!

alert:
  enabled: false
  heading:
  text:

social-media:
  - service: twitter
    link: "https://x.com/MyAgency"
  - service: vimeo
    link: "https://vimeo.com/MyAgency"
  - service: instagram
    link: "https://www.instagram.com/MyAgency"
  - service: facebook
    link: "https://www.facebook.com/MyAgency"

# Used to construct absolute URLs throughout the site
url: "https://www.MyAgency.gov"

# Digital Analytics Program (DAP) configuration
dap:
  agency:

# Site Navigation
secondary_navigation:
  - name: Contact us
    url: "/contact/"

footer_navigation:
  - name: Accessibility statement
    url: "/policies/#accessibility-statement"
  - name: Freedom of Information Act (FOIA)
    url: "/policies/#freedom-of-information-act-foia"
  - name: Equal employment
    url: "/policies/#equal-employment"
  - name: External links
    url: "/policies/#external-links"
  - name: Privacy policy
    url: "/policies/#privacy-policy"
  - name: Vulnerability disclosure policy
    url: "/policies/#vulnerability-disclosure-policy"
  - name: Have a question about government services? Contact USA.gov.
    url: https://usa.gov/

# Search.gov configuration
#
# 1. Create an account with Search.gov https://search.usa.gov/signup
# 2. Add a new site.
# 3. Add your site/affiliate name here.
searchgov:
  api: https://api.gsa.gov/technology/searchgov/v2/results/i14y
  # Only change this if you're using a CNAME. Learn more here: https://search.gov/manual/cname.html
  endpoint: https://search.usa.gov

  # Replace this with your search.gov account.
  affiliate: MyAgency

  # Replace this with your access key.
  access_key:
  # This renders the results within the page instead of sending to user to search.gov.
  inline: true

  # This allows Search.gov to present relevant type-ahead search suggestions in your website's search box.
  # If you do not want to present search suggestions, set this value to false.
  suggestions: true
